# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='tq_type',
            field=models.IntegerField(choices=[(1, 'One answer'), (2, 'N answers'), (3, 'Rate on scale')]),
        ),
    ]
