# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20160804_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tqanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
